runtime: nodejs22
service: queezbud-app

env_variables:
  NODE_ENV: production

entrypoint: node ./server/server.mjs

automatic_scaling:
  # Optional: adjust as needed
  min_instances: 1
  max_instances: 2

handlers:
  - url: /.*
    script: auto
    secure: always
    redirect_http_response_code: 301
