name: 'Deploy to Cloud Run from Source'

on:
  push:
    branches:
      - main
    paths:
      - 'apps/queezbud-app/**'
      - 'libs/**'
      - 'gcp/app.yaml'

jobs:
  deploy:
    runs-on: 'ubuntu-latest'

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: 'Checkout'
        uses: 'actions/checkout@v4' 
    
      - name: Setup Node.js and npm
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm ci --legacy-peer-deps

      - name: Build the application
        run: npx nx build queezbud-app

      - name: Copy app.yaml
        run: cp gcp/app.yaml dist/apps/queezbud-app/app.yaml
      - name: List dist directory
        run: ls -la dist/apps/queezbud-app

      - name: Google Cloud Auth
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Set up Cloud SDK
        uses: 'google-github-actions/setup-gcloud@v2'

      - name: Checking credentials of current service account
        run: | 
          gcloud projects get-iam-policy ${{ secrets.GCP_PROJECT_ID }} \
            --flatten="bindings[].members" \
            --filter="bindings.members:serviceAccount:queezbud-app@queezbud.iam.gserviceaccount.com" \
            --format="value(bindings.role)"

      # - name: Deploy to Google App Engine
      #   run: gcloud app deploy dist/apps/queezbud-app
